from .shot_node import NODE_CLASS_MAPPINGS as SHOT_NODE_MAPPINGS
from .shot_node import NODE_DISPLAY_NAME_MAPPINGS as SHOT_DISPLAY_MAPPINGS
from .image_node import NODE_CLASS_MAPPINGS as IMAGE_NODE_MAPPINGS
from .image_node import NODE_DISPLAY_NAME_MAPPINGS as IMAGE_DISPLAY_MAPPINGS
from .read_node import NODE_CLASS_MAPPINGS as READ_NODE_MAPPINGS
from .read_node import NODE_DISPLAY_NAME_MAPPINGS as READ_DISPLAY_MAPPINGS

NODE_CLASS_MAPPINGS = {**SHOT_NODE_MAPPINGS, **IMAGE_NODE_MAPPINGS, **READ_NODE_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**SHOT_DISPLAY_MAPPINGS, **IMAGE_DISPLAY_MAPPINGS, **READ_DISPLAY_MAPPINGS}
WEB_DIRECTORY = "./js"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
